import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const tommorow = localFont({
  src: [
  {
    path: './fonts/Tomorrow-Black.ttf',
    weight: '900',
    style: 'normal',

  },  {
    path: './fonts/Tomorrow-ExtraBold.ttf',
    weight: '800',
    style: 'normal',

  },  {
    path: './fonts/Tomorrow-Bold.ttf',
    weight: '700',
    style: 'normal',

  },  {
    path: './fonts/Tomorrow-SemiBold.ttf',
    weight: '600',
    style: 'normal',

  },  {
    path: './fonts/Tomorrow-Medium.ttf',
    weight: '500',
    style: 'normal',

  },  {
    path: './fonts/Tomorrow-Regular.ttf',
    weight: '400',
    style: 'normal',

  },  {
    path: './fonts/Tomorrow-Thin.ttf',
    weight: '200',
    style: 'normal',

  },  {
    path: './fonts/Tomorrow-ExtraLight.ttf',
    weight: '100',
    style: 'normal',

  },
  ],
})


const workSans = localFont({
  src: [
  {
    path: './fonts/WorkSans-Black.ttf',
    weight: '900',
    style: 'normal',

  },  {
    path: './fonts/WorkSans-ExtraBold.ttf',
    weight: '800',
    style: 'normal',

  },  {
    path: './fonts/WorkSans-Bold.ttf',
    weight: '700',
    style: 'normal',

  },  {
    path: './fonts/WorkSans-SemiBold.ttf',
    weight: '600',
    style: 'normal',

  },  {
    path: './fonts/WorkSans-Medium.ttf',
    weight: '500',
    style: 'normal',

  },  {
    path: './fonts/WorkSans-Regular.ttf',
    weight: '400',
    style: 'normal',

  },  {
    path: './fonts/WorkSans-Thin.ttf',
    weight: '200',
    style: 'normal',

  },  {
    path: './fonts/WorkSans-ExtraLight.ttf',
    weight: '100',
    style: 'normal',

  },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={tommorow.className}
      >
        {children}
      </body>
    </html>
  );
}
